### ISSUE TITLE
there is no code

### ISSUE THREAD

**Issue by spsquared** [maitian352/Blue-Pixel-Simulator#1]
The repository is empty even though the game has code

bugbugbugbugbugbugbugbugbugbugbugbugbugbugbugbugbugbugbugbug

**Comment by spsquared** [comment]
there is still no code

**Comment by spsquared** [comment]
I can't even add the code by creating a fork because it's literally empty

**Comment by spsquared** [comment]
I need push access to add code, bug bug fix now

**Comment by SampleProvider** [comment]
ok

**Comment by spsquared** [comment]
I still don't have push access
![image](https://github.com/maitian352/Blue-Pixel-Simulator/assets/67865358/b2c5fe01-c0f4-4731-8538-8189d0559a4b)

**Comment by spsquared** [comment]
ok fixed #1
